name: anime_discovery
description: "MyAnimeList client app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  http_interceptor: ^2.0.0-beta.8
  image: ^4.2.0
  jikan_api: ^2.2.1
  provider: ^6.1.2
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - .env
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
        - asset: fonts/Lato-Black.ttf
        - asset: fonts/Lato-BlackItalic.ttf
        - asset: fonts/Lato-BoldItalic.ttf
        - asset: fonts/Lato-Light.ttf
        - asset: fonts/Lato-LightItalic.ttf
          weight: 700
